### ISSUE TITLE
Exponets calculations bug

### ISSUE THREAD

**Issue by Seg-Faulted** [TheCriticalGamer/JavaCalculator#1]
_In the current implementation of the calculator program, there appears to be unexpected behavior related to the recognition of mathematical operators. Although the initial implementation utilized if-else statements to differentiate between operators such as addition, subtraction, multiplication, division, and exponentiation, the program seems to be misinterpreting the input under certain conditions._

Upon thorough examination, it was discovered that the issue stems from the method used to identify the mathematical operators within the user input string. Initially, the code employed the String.contains() method to check for the presence of specific operators like *, /, +, -, and **. However, despite this approach seemingly adequate, the program occasionally fails to distinguish between certain operators accurately.

For instance, when the input includes both the multiplication operator (*) and the exponentiation operator (**), the program erroneously prioritizes the multiplication operator due to the shared character *. As a result, it executes the corresponding block of code for multiplication instead of recognizing the intended exponentiation operation.

This unexpected behavior raises concerns about the reliability and accuracy of the calculator program, as it could potentially yield incorrect results or unexpected outcomes for users. Therefore, investigating and resolving this issue is crucial to ensure the proper functioning of the calculator and enhance user experience.

**Comment by TheCriticalGamer** [comment]
fixed, check changelog of https://github.com/TheCriticalGamer/JavaCalculator/compare/v1.0.0-rc1...v1.1.0-rc1

**Comment by Seg-Faulted** [comment]
Fixed with: https://github.com/TheCriticalGamer/JavaCalculator/releases/tag/v1.1.0-rc1
